import type { Metadata } from 'next'
import './globals.css'
import Link from 'next/link'
import ReactQueryProviders from '@/src/utils/ReactQueryProviders'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" data-theme="winter">
      <body>
        <header>
          <div>
            <Link href="/">Logo</Link>
          </div>
          <nav>
            <Link href="/">홈</Link>
            <Link href="/about">소개</Link>
            <Link href="/article">게시판</Link>
            <Link href="/member/login">로그인</Link>
          </nav>
        </header>
        <main>
          <ReactQueryProviders>{children}</ReactQueryProviders>
        </main>
      </body>
    </html>
  )
}
